services:
  nginx:
    volumes:
      - ./logs/prod/nginx:/var/log/nginx

  api:
    build:
      context: .
      target: production
    # command: fastapi run --host 0.0.0.0 --port 8000 --workers 4
    command: >
      gunicorn app.main:app 
      --workers 1 
      --worker-class uvicorn.workers.UvicornWorker 
      --bind 0.0.0.0:8000 
      --timeout 120
      --error-logfile -
      --access-logfile -
    volumes:
      - ./logs/prod:/app/logs

  stream_worker:
    build:
      context: .
      target: production
    command: faststream run app.stream_app:app
    volumes:
      - ./logs/prod:/app/logs

  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

volumes:
  pg_data:
    name: ai_tg_postgres_prod_data
  pgadmin_data:
    name: ai_tg_pgadmin_prod_data
  rabbitmq_data:
    name: ai_tg_rabbitmq_prod_data
  redis_data:
    name: ai_tg_redis_prod_data
  # stream_docs_static:
  #   name: ai_tg_stream_docs_static_prod_data
