[project]
name = "ai-tg-post-creator"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Andrii Toptun", email = "andrii.toptun@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "beautifulsoup4>=4.15.0",
    "fastapi-pagination>=0.15.14",
    "fastapi[standard]>=0.136.3",
    "faststream[cli,rabbit]>=0.7.1",
    "gunicorn>=26.0.0",
    "sqlalchemy>=2.0.50",
    "telethon>=1.43.2",
]

[dependency-groups]
dev = [
    "debugpy>=1.8.21",
    "faker>=40.23.0",
    "pytest>=9.0.3",
    "pytest-asyncio>=1.4.0",
    "pytest-env>=1.6.0",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
python_classes = ["Test", "Describe"]
python_functions = ["test_", "it_", "and_", "but_", "they_"]
python_files = ["test_*.py",]
testpaths = ["tests",]
env_files = [
    ".env.test"
]
