"""Add naming convention

Revision ID: a5c208b630cb
Revises: 51b5b0f1e7e1
Create Date: 2026-06-13 13:17:01.953139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c208b630cb'
down_revision: Union[str, Sequence[str], None] = '51b5b0f1e7e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('keywords_word_key'), 'keywords', type_='unique')
    op.create_unique_constraint(op.f('uq_keywords_word'), 'keywords', ['word'])
    op.drop_constraint(op.f('news_items_title_key'), 'news_items', type_='unique')
    op.drop_constraint(op.f('news_items_url_key'), 'news_items', type_='unique')
    op.create_unique_constraint(op.f('uq_news_items_title'), 'news_items', ['title'])
    op.create_unique_constraint(op.f('uq_news_items_url'), 'news_items', ['url'])
    op.drop_constraint(op.f('sources_url_key'), 'sources', type_='unique')
    op.create_unique_constraint(op.f('uq_sources_url'), 'sources', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_sources_url'), 'sources', type_='unique')
    op.create_unique_constraint(op.f('sources_url_key'), 'sources', ['url'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_news_items_url'), 'news_items', type_='unique')
    op.drop_constraint(op.f('uq_news_items_title'), 'news_items', type_='unique')
    op.create_unique_constraint(op.f('news_items_url_key'), 'news_items', ['url'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('news_items_title_key'), 'news_items', ['title'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_keywords_word'), 'keywords', type_='unique')
    op.create_unique_constraint(op.f('keywords_word_key'), 'keywords', ['word'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
