"""Cascade delete posts when delete news item

Revision ID: 51b5b0f1e7e1
Revises: 99240f3a0e00
Create Date: 2026-06-13 12:56:54.890893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51b5b0f1e7e1'
down_revision: Union[str, Sequence[str], None] = '99240f3a0e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('posts_news_id_fkey'), 'posts', type_='foreignkey')
    op.create_foreign_key('posts_news_id_fkey', 'posts', 'news_items', ['news_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_news_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_news_id_fkey'), 'posts', 'news_items', ['news_id'], ['id'])
    # ### end Alembic commands ###
