"""Update schema

Revision ID: 7d712ef5ede1
Revises: b1c2d3e4f567
Create Date: 2026-06-15 19:33:40.714921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d712ef5ede1'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_items_published_at'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_source'), table_name='news_items')
    op.drop_constraint(op.f('uq_news_items_source_title'), 'news_items', type_='unique')
    op.drop_constraint(op.f('uq_news_items_source_url'), 'news_items', type_='unique')
    op.create_unique_constraint(op.f('uq_news_items_title'), 'news_items', ['title'])
    op.create_unique_constraint(op.f('uq_news_items_url'), 'news_items', ['url'])
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    op.drop_constraint(op.f('uq_news_items_url'), 'news_items', type_='unique')
    op.drop_constraint(op.f('uq_news_items_title'), 'news_items', type_='unique')
    op.create_unique_constraint(op.f('uq_news_items_source_url'), 'news_items', ['source', 'url'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_news_items_source_title'), 'news_items', ['source', 'title'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_news_items_source'), 'news_items', ['source'], unique=False)
    op.create_index(op.f('ix_news_items_published_at'), 'news_items', ['published_at'], unique=False)
    # ### end Alembic commands ###
